"""Restyle the verified procedural corpus into the v3 conditional caveman register.

The procedural traces (`traces.jsonl`) were generated by executing GoalFamily oracles in
the REAL sandbox, so they are expensive to regenerate. This script re-styles them WITHOUT
re-running the sandbox: it parses each wire back into a Conversation, touches only the two
things that carry the persona/register signal, and re-serializes.

What changes (caveman fraction only):
  * `conv.system` is set to a caveman persona variant (procedural traces have no system,
    so this is the persona conditioner — same mechanism as the conversational corpus).
  * the TERMINAL report turn (the lone AssistantMsg with no tool_calls, e.g. "Done. 4")
    is reframed through `caveman_report`, which keeps the echoed payload verbatim.

What is NEVER touched:
  * CALL turns (AssistantMsg WITH tool_calls) — the wire parser (`ast.literal_eval`) would
    break if the register bled into a CALL line, collapsing RLVR reward.
  * ToolResult turns (RESULT[...] payloads + harness trailer).
  * numbers / code / identifiers inside the report echo (appended verbatim, not restyled).

The control fraction is emitted byte-for-byte unchanged (system=None, plain "Done. X"),
which both teaches the persona->register mapping and keeps the procedural format identical
to the v2 distribution so v3 does not regress tool-call format.

Usage:
    python -m orkun.scripts.restyle_procedural \\
        --orkish-repo /Users/.../Orkish \\
        --in  orkun/data/sft_proc/traces.jsonl \\
        --out orkun/data/sft_proc/traces_caveman.jsonl \\
        --caveman-frac 0.85 --fr-rate 0.12 --seed 0
"""
from __future__ import annotations

import argparse
import json
import random
import re
import sys
from collections import Counter
from pathlib import Path

from orkun.style.caveman import caveman_report, persona

_DONE_RE = re.compile(r"^Done\.\s*(.*)$", re.DOTALL)


def _restyle_report(text: str, rng: random.Random) -> str:
    """Reframe a terminal report into the caveman register, echo kept verbatim."""
    m = _DONE_RE.match(text)
    echo = m.group(1) if m else text
    return caveman_report(echo or None, rng)


def restyle_record(rec: dict, caveman: bool, rng: random.Random, parse, serialize) -> dict:
    if not caveman:
        return {"wire": rec["wire"], "task": rec.get("task", ""), "register": "plain"}
    conv = parse(rec["wire"])
    conv.system = persona(rng)
    for turn in conv.turns:
        # Only the prose report turn: AssistantMsg with no tool_calls. CALL turns carry
        # tool_calls and must round-trip untouched; ToolResult/UserMsg are not AssistantMsg.
        if type(turn).__name__ == "AssistantMsg" and not getattr(turn, "tool_calls", None):
            turn.text = _restyle_report(turn.text, rng)
    return {"wire": serialize(conv), "task": rec.get("task", ""), "register": "caveman"}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--orkish-repo", required=True, type=Path)
    ap.add_argument("--in", dest="in_path", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path)
    ap.add_argument("--caveman-frac", type=float, default=0.85)
    ap.add_argument("--fr-rate", type=float, default=0.12)
    ap.add_argument("--seed", type=int, default=0)
    args = ap.parse_args()

    s = str(args.orkish_repo)
    if s not in sys.path:
        sys.path.insert(0, s)
    from infer.monkey_wire import parse, serialize

    rng = random.Random(args.seed)
    reg = Counter()
    out_recs: list[dict] = []
    with args.in_path.open(encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            caveman = rng.random() < args.caveman_frac
            out = restyle_record(rec, caveman, rng, parse, serialize)
            reg[out["register"]] += 1
            out_recs.append(out)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w", encoding="utf-8") as f:
        for rec in out_recs:
            f.write(json.dumps(rec, ensure_ascii=False) + "\n")

    print(f"=== procedural restyled: {len(out_recs)} records -> {args.out} ===")
    print("register split:", dict(reg))


if __name__ == "__main__":
    main()
